import {redirect} from 'next/navigation';
import {AppNav} from '@/app/components/AppNav';
import {NibUploader} from '@/app/components/NibUploader';
import {TenderNotifications} from '@/app/components/TenderNotifications';
import {OpportunityPicks} from '@/app/components/OpportunityPicks';
import {TenderSearchTrigger} from '@/app/components/TenderSearchTrigger';
import {getUserDashboard} from '@/lib/database';
import {resolveViewer} from '@/lib/viewer';
export const dynamic='force-dynamic';
type Row=Record<string,string|number|null>;
function dateLabel(value:string|number|null){return value?new Date(String(value)).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}):'Belum ditentukan'}
export default async function UserDashboard({searchParams}:{searchParams:Promise<{view?:string}>}){const{view}=await searchParams;const viewer=await resolveViewer(view);if(!viewer)redirect('/');if(viewer.role==='admin')redirect('/admin');const data=await getUserDashboard(viewer.slug).catch(()=>null);if(!data)redirect('/');const stats=data.stats as {total?:number;tenders?:number;direct_procurements?:number;average_match?:number};const trackers=data.trackers as Row[];const opportunities=data.opportunities as Row[];const notifications=data.notifications as Row[];const documents=data.nibDocuments as Row[];const kbli=data.kbli as Row[];return <main className="app-shell"><AppNav name={data.user.name} role="user"/><section className="workspace"><header className="topbar"><div><span className="kicker">PROCUREMENT USER</span><h1>Halo, {data.user.name}.</h1><p>Temukan dan prioritaskan pekerjaan Tender atau Pengadaan Langsung (PL).</p></div><div className="topbar-actions"><span className="live-badge">● Mesin pencari aktif</span><span className="avatar">{data.user.name.slice(0,2).toUpperCase()}</span></div></header>
<TenderNotifications items={notifications} slug={viewer.slug}/>
<TenderSearchTrigger source={(data.searchSource as Row|null)??null} run={(data.searchRun as Row|null)??null} view={view}/>
<section className="profile-banner" id="overview"><div><span className="kicker light">PROFIL PENYEDIA</span><h2>{data.user.headline}</h2><p>{data.user.location} · Kesiapan profil {data.user.profile_completion}% · {kbli.length} KBLI tersimpan</p><a className="button button-yellow" href="#nib">Upload NIB <span>→</span></a></div><div className="progress-display"><strong>{data.user.profile_completion}</strong><span>%</span><small>Vendor readiness</small></div></section>
<section className="metric-grid"><article><span>01</span><small>Total peluang cocok</small><strong>{stats.total??0}</strong><em>Tender + PL aktif</em></article><article><span>02</span><small>Paket Tender</small><strong>{stats.tenders??0}</strong><em>KBLI cocok persis</em></article><article><span>03</span><small>Pengadaan Langsung</small><strong>{stats.direct_procurements??0}</strong><em>KBLI cocok persis</em></article><article className="yellow"><span>04</span><small>Rata-rata match</small><strong>{stats.average_match??0}%</strong><em>Kecocokan penyedia</em></article></section>
<section className="source-notice"><strong>DATA RESMI &amp; AKTIF</strong><p>Hanya paket SPSE dengan KBLI yang sama dan jadwal akhir belum lewat yang disimpan dan ditampilkan.</p>{data.searchSource&&<a href={String((data.searchSource as Row).source_url)} target="_blank" rel="noreferrer">Buka SPSE resmi ↗</a>}</section>
<OpportunityPicks items={opportunities}/>
<section className="dashboard-grid procurement-grid tracker-nib"><article className="data-panel" id="tracker"><div className="section-heading"><div><span className="kicker">BID PIPELINE</span><h2>Tracker penawaran</h2></div><span className="record-count">{trackers.length} paket</span></div><div className="application-list">{trackers.map((item)=><div className="application-row procurement-row" key={String(item.id)}><span className="company-initial">{String(item.procurement_type)==='Tender'?'T':'PL'}</span><div><strong>{String(item.title)}</strong><small>{String(item.tender_code)} · {String(item.lpse)}</small><small>{String(item.next_action??'Belum ada tindak lanjut')} · {dateLabel(item.due_at)}</small></div><span className="stage-badge">{String(item.stage)}</span><b>{Number(item.match_score??0)}%</b></div>)}</div></article><NibUploader documents={documents} kbli={kbli} slug={viewer.slug}/></section>
</section></main>}
